### ISSUE TITLE
Update header content

### ISSUE THREAD

**Issue by oraNod** [ansible/jinja-docsite#11]
Make sure top-level nav has all the content. Links work. Background color is set.

**Comment by samccann** [comment]
Right now, I find the top nav difficult to notice. Took me a few visits before I realized it was even there... Maybe because it's the same background color right now?


![image](https://user-images.githubusercontent.com/30267855/222552439-61b80ea5-6786-4633-a00b-326987360fb7.png)

**Comment by oraNod** [comment]
Closing this issue as I think it's been resolved in other PRs.
