### ISSUE TITLE
Update footer content

### ISSUE THREAD

**Issue by oraNod** [ansible/jinja-docsite#12]
License and copyright statement. Other verbiage, links as needed.

**Comment by samccann** [comment]
Can we make it bigger? I think we may need some more things listed at the bottom.  Tho  I can't say what those things might be, but would be good if it were able to have lists like this:
![image](https://user-images.githubusercontent.com/30267855/222553703-42520879-696f-4637-bd54-4fef0f90b1e4.png)

(not identical, but quick access to common things on the bottom of every one of the docsite/website pages would be good imo

**Comment by oraNod** [comment]
@samccann Yeah we can do that. But I would add the links and stuff as a grid on top of the redhat footer. We should probably do that as part of the main site rather than the new docsite.

**Comment by samccann** [comment]
@oraNod my nickel - keep the same... erm... sitemap/footer on all HTML pages that are not actual rst-to-html docSET pages.   So yeah, not something we need to nitpick here since we're working on just docs landing pages prototyping.

**Comment by oraNod** [comment]
@samccann it would be the same sitemap/footer on all pages. I just mean that they are two separate components.
