### ISSUE TITLE
Determine the requirements for the MVP of the docsite

### ISSUE THREAD

**Issue by samccann** [ansible/jinja-docsite#58]
Feedback from the DaWGs meeting suggests the following requirements before these pages replace existing docs.ansible.com:

- [ ] no content regressions, including translations and archive pages
- [ ] early-user/tester feedback. maybe a focus group to use it for a time?

**Comment by oraNod** [comment]
@samccann I just made an edit to boil things down to the nitty gritty. I think #1 has been implied from the beginning but I agree it's good to have that clearly written down somewhere. I also think there are issues for all the content so maybe we need to list them or link them here.

#2 is also in plan but, again, maybe not explicitly called out somewhere. I think we have two choices. option one is what we're currently planning, to replace the content on docs.ansible.com and add a toggle for the "old" site.

option two is what I think you have been advocating. we leave the prototype on GitHub pages and add the toggle to docs.ansible.com that invites users to try out the new navigation.

there is an option three to actually have focus group style testing but I feel like that is superfluous and won't actually give us better feedback than either of the other options.

**Comment by samccann** [comment]
@oraNod couple of followon thoughts -
- we could point reddit folks at the prototype for feedback. I've had some good feedback come from that approach before.
- at least three people so far have been tripped up by the 'other resources' not being an obvious continuation of the journey so to speak.  We could potentially wordsmith it to 'continue your user/dev/contributor journey' or make it a button or something that catches the eye. It feels like an MVP item to me because w/o it, people aren't going to find the user page, community page, dev page, etc.

**Comment by samccann** [comment]
should also mention some of the responsive design problems pointed out have been fixed. My not work on a phone yet, but much better imo now.

**Comment by oraNod** [comment]
yeah responsive stuff is on the mvp list for sure. there's already an issue so we just need to add the label.

the Reddit approach sounds good to me. maybe we can talk about that one at the team meeting on Monday?

yeah I saw that feedback about the journey continuation but haven't had a chance to tackle it yet.

it's already a button so I was thinking about a small icon or maybe changing the font weight. also def wordsmith it. we'll see but I agree that needs to be part of the mvp too.

**Comment by oraNod** [comment]
@samccann I'm going to close this issue. We're tracking everything for the MVP with that label: https://github.com/ansible/jinja-docsite/issues?q=is%3Aissue+is%3Aopen+label%3AMVP

As for the user feedback testing, we're providing feedback mechanisms and the possibility to revert to the old/current site. While setting up early adopter testing and focus groups is a reasonable suggestion it is a time-intensive process that doesn't quite fit the timelines we're working towards, especially if you want to get high-quality feedback.
