### ISSUE TITLE
Keep ansible.com top-level navigation

### ISSUE THREAD

**Issue by oraNod** [ansible/jinja-docsite#74]
- Can you make the header of the docsite exactly the same as current [docs.ansible.com](http://docs.ansible.com/) (with Product, Blog, Community etc....)
- Create a sub header with Ansible core, Ansible ecosystem, Ansiible automatioin platform, Join the communiity
- On that sub header, can you rename Ansible automation platform with Red Hat Ansible Automation Platform

**Comment by samccann** [comment]
Hmm... gut reaction - not sure we want the same header as current docs.ansible.com. This is a step in the direction of a community-only site and feels like we should be 'testing' our own new header on these pages. Tho I can understand that it would be jarring going from ansible.com to this new set of pages...

**Comment by oraNod** [comment]
For the record I'm not in favour of this but it's feedback that has been passed to me. We can at least give it a whirl in a PR and maybe put it to a vote or something. As you said, and in fairness, docs.ansible.com is still under ansible.com even though it's really just a link. So let's see how it goes...
